using UnityEngine;
using UnityEngine.InputSystem;

public class LeftTriggerByReference : MonoBehaviour
{
    // Inspector ä¸­æ‹–å…¥â€œXRI LefhtHand Interaction/Activateâ€åŠ¨ä½?
    public InputActionReference LeftTriggerReference;
    public bool isLeftTriggerPressed = false;

 
    void Update()
    {
        var action = LeftTriggerReference?.action;
        if (action == null) return;

        if (action.WasPressedThisFrame())
        {
            Debug.Log("å³æ‰³æœºæŒ‰ä¸? (InputActionReference)");
            isLeftTriggerPressed = true;
        }

        if (action.WasReleasedThisFrame())
        {
            Debug.Log("å³æ‰³æœºæ¾å¼€");
            isLeftTriggerPressed = false;
        }

        float value = action.ReadValue<float>();
        if (value > 0.1f)
        {
            Debug.Log($"å³æ‰³æœºæŒ‰å‹å€?: {value}");
        }
    }
}
